name: dart_week_mobile
description: A new Flutter project.
version: 1.0.0+1

scripts:
  mobx_build: flutter pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  sliding_sheet: ^0.3.3
  combos: ^1.2.0
  oktoast: ^2.3.2
  get: ^1.12.0
  flutter_masked_text: ^0.8.0
  shared_preferences: ^0.5.6+3
  intl: ^0.16.0

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
